name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Garde tout en minuscules pour GHCR
  IMAGE_NAME: ghcr.io/paullalarme/maracorp-signature:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u paullalarme --password-stdin

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Push image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH (root)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}     # 193.70.33.48
          username: ${{ secrets.SSH_USER }} # root
          key: ${{ secrets.SSH_KEY }}       # clé privée OPENSSH (BEGIN/END)
          script: |
            set -euo pipefail
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u paullalarme --password-stdin
            docker compose -f /opt/maracorp/docker-compose.yml pull
            docker compose -f /opt/maracorp/docker-compose.yml up -d
            docker ps
